openapi: 3.0.3
info:
  title: Sample API
  termsOfService: https://example.com/terms/
  contact:
    name: Customer Support
    url: https://example.com/support
    email: support@example.com
  license:
    name: MIT License
    url: https://opensource.org/lisences/MIT
  version: 1.0.0
servers:
- url: "http://api.example.com/{version}"
  description: Production Environment
  variables:
    version:
      description: API version
      enum:
      - v1
      - v2
      default: v2
- url: "http://localhost:{port}"
  description: Local development
  variables:
    port:
      enum:
      - "3000"
      - "8000"
      - "8080"
      default: "3000"
- url: https://it1.example.com
  description: Integration test
- url: https://staging.example.com
  description: Staging environment
- url: "https://api-dev.example.com/{version}"
  description: Develop environment
  variables:
    version:
      description: API version
      enum:
      - v1
      - v2
      - v3
      default: v3
tags:
- name: reviews
  description: Shop review operation
paths:
  /shops/{shopId}/reviews:
    get:
      tags:
      - shops
      - reviews
      summary: Get specified shop reviews
      description: "(description): Get specified shop reviews"
      operationId: shopsShopIdReviewsGET
      parameters:
      - name: shopId
        in: path
        description: Shop identifier
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Success operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Review'
                x-content-type: application/json
      deprecated: false
      security: []
      x-swagger-router-controller: Shops
    post:
      tags:
      - shops
      - reviews
      summary: Create review
      description: Create review
      operationId: shopsShopIdReviewsPOST
      parameters:
      - name: shopId
        in: path
        description: Shop identifier
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: X-Api-Key
        in: header
        description: Request user's identifier
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: XXXX-XXXX-XXXX-XXXX
      - name: token
        in: cookie
        description: One time token
        required: false
        style: form
        explode: true
        schema:
          type: string
        example: token-aejtwb;ltkgtaherpuighb0yw5pkhj
      requestBody:
        description: Contents of review
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Review'
        required: true
      responses:
        "201":
          description: Success operation
          headers:
            location:
              description: New URL of created review
              style: simple
              explode: false
              schema:
                type: string
                format: url
        "400":
          description: Client error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientError'
      deprecated: false
      security:
      - apikey_auth: []
      x-swagger-router-controller: Shops
  /hello-world:
    get:
      summary: Sample API initial test
      description: 'return string "Hello world from Sample API!!" '
      operationId: hello_worldGET
      responses:
        "200":
          description: Success operation
          content:
            application/json:
              schema:
                type: string
                example: Hello world from Sample API!!
                x-content-type: application/json
      x-swagger-router-controller: Default
components:
  schemas:
    Review:
      type: object
      properties:
        score:
          type: integer
          example: 3
        comment:
          type: string
          example: おいしかった
      example:
        score: 3
        comment: おいしかった
    ClientError:
      type: object
      properties:
        code:
          type: string
          example: 1234-001
        type:
          type: string
          example: not a integer
        message:
          type: string
          example: score is not a integer
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ClientError_errors'
    SampleInt:
      maximum: 100
      exclusiveMaximum: true
      minimum: 0
      exclusiveMinimum: false
      type: integer
    SampleString:
      maxLength: 20
      minLength: 10
      type: string
      nullable: true
    SampleBoolean:
      type: boolean
    SampleObject:
      type: object
      properties:
        shop:
          $ref: '#/components/schemas/SampleObject_shop'
    ClientError_errors:
      type: object
      properties:
        field:
          type: string
          example: score
        code:
          type: string
          example: 1234-001
    SampleObject_shop:
      type: object
      properties:
        score:
          type: integer
          enum:
          - 1
          - 2
          - 3
          - 4
          - 5
        comment:
          type: string
  responses:
    "400-BadRequest":
      description: Client error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ClientError'
  parameters:
    ShopId:
      name: shopId
      in: path
      description: Shop identifier
      required: true
      style: simple
      explode: false
      schema:
        type: string
  securitySchemes:
    apikey_auth:
      type: apiKey
      description: API key authorization
      name: X-Api-Key
      in: header
